# Generated by Django 4.2.1 on 2023-05-05 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_create_time_alter_blogmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 12, 12, 24, 578455, tzinfo=datetime.timezone.utc)),
        ),
    ]
