# Generated by Django 4.2.1 on 2023-05-04 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 19, 53, 19, 804051, tzinfo=datetime.timezone.utc))),
                ('image', models.ImageField(upload_to='cover/')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
            ],
        ),
    ]
