# Generated by Django 4.2.1 on 2023-05-04 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 20, 11, 40, 95163, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='media/cover_blog/'),
        ),
    ]
