# Generated by Django 4.2.1 on 2023-05-05 07:27

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blogmodel_create_time_alter_blogmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 7, 27, 3, 669881, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
