# Generated by Django 4.2.1 on 2023-05-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blogmodel_create_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogModel',
        ),
    ]
